[project]
name = "robot-code-2026"
version = "0.1.0"
description = ""
authors = [
    {name = "TheNerdyFunnyComedian",email = "hudsonjimenez@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "robot_code_2026", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
